spring:
  profiles:
    active: prod
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: encrypt
server:
  port: 8081
  servlet:
    context-path: /api/encrypt
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qiaohx.encrypt.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
